name: TCC_Core
version: '${project.version}'
main: cc.leafed.tcc_core.Core
api-version: '1.20'
author: Aduhkiss
commands:
  portal:
    description: Server Selection GUI
    permission: thecloudyco.portal
    aliases: ["server"]
  ip:
    description: Find the real IP address of a member
    permission: thecloudyco.ip
  sc:
    description: Send a staff chat message
    permission: thecloudyco.staff
    aliases: ["s"]
  find:
    description: Find what server a given player is connected to
    permission: thecloudyco.find
  skin:
    description: Update your current Minecraft skin
    permission: thecloudyco.staff
  membership:
    description: Access your membership details
  hub:
    description: Send yourself back to the hub
permissions:
  thecloudyco.portal:
    default: true
  thecloudyco.ip:
    default: op
  thecloudyco.staff:
    default: op
  thecloudyco.find:
    default: op